### ISSUE TITLE
Crash + Blame prints all RS structures.

### ISSUE THREAD

**Issue by RDKRACZ** [TelepathicGrunt/RepurposedStructures-Fabric#112]
I updated a bunch of mods at once and now I can't load and create words. It's just crashing. Reporting here because RS was one of the mods I updated and it's being mentioned by the Blame. I will try to narrow down which mods are causing this if this is not RS cause.
This is just a small part of the log. 

<details>

```
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/badlands.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/dark_forest.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/dark_forest_post_process.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/desert.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/end.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/icy.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/jungle.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/jungle_post_process.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/mushroom_high.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}


[11:37:28] [main/ERROR]: 
****************** Blame Report 1.16.4-2.4.1 ******************

 Failed to load resource file: repurposed_structures:worldgen/processor_list/dungeons/mushroom_low.json

 Reason stated: Not a json array

 Possibly helpful hint (hopefully): 
     This error typically means you need an certain kind of JSON array surrounding
     the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
     check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1

 Prettified form of the broken JSON: 
{
  "processors": [
    {
      "rules": [
        {
          "output_state": {
            "Name": "minecraft:mossy_cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:cobblestone",
            "probability": 0.01,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:cobblestone"
          },
          "input_predicate": {
            "block": "minecraft:barrel",
            "probability": 0.85,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "rotation": "12"
            },
            "Name": "minecraft:wither_skeleton_skull"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.005,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Name": "minecraft:air"
          },
          "input_predicate": {
            "block": "minecraft:skeleton_skull",
            "probability": 0.6,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
        {
          "output_state": {
            "Properties": {
              "facing": "north",
              "lit": "false",
              "signal_fire": "false",
              "waterlogged": "false"
            },
            "Name": "minecraft:campfire"
          },
          "input_predicate": {
            "block": "minecraft:campfire",
            "probability": 0.15,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        }
      ],
      "processor_type": "minecraft:rule"
    }
  ]
}
```

</details>

Also at the bottom of the crash log there was
<details>

```
[11:37:30] [main/ERROR]: Error loading registry data: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:mossy_cobblestone"},"input_predicate":{"block":"minecraft:cobblestone","probability":0.01,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:cobblestone"},"input_predicate":{"block":"minecraft:barrel","probability":0.85,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"rotation":"12"},"Name":"minecraft:wither_skeleton_skull"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.005,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:air"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.6,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"facing":"north","lit":"false","signal_fire":"false","waterlogged":"false"},"Name":"minecraft:campfire"},"input_predicate":{"block":"minecraft:campfire","probability":0.15,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}]}
[11:37:30] [main/ERROR]: Pool element: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:mossy_cobblestone"},"input_predicate":{"block":"minecraft:cobblestone","probability":0.01,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:cobblestone"},"input_predicate":{"block":"minecraft:barrel","probability":0.85,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"rotation":"12"},"Name":"minecraft:wither_skeleton_skull"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.005,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:air"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.6,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"facing":"north","lit":"false","signal_fire":"false","waterlogged":"false"},"Name":"minecraft:campfire"},"input_predicate":{"block":"minecraft:campfire","probability":0.15,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}]}
[11:37:30] [main/ERROR]: Pool element: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:mossy_cobblestone"},"input_predicate":{"block":"minecraft:cobblestone","probability":0.01,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:cobblestone"},"input_predicate":{"block":"minecraft:barrel","probability":0.85,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"rotation":"12"},"Name":"minecraft:wither_skeleton_skull"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.005,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:air"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.6,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"facing":"north","lit":"false","signal_fire":"false","waterlogged":"false"},"Name":"minecraft:campfire"},"input_predicate":{"block":"minecraft:campfire","probability":0.15,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}]}
[11:37:30] [main/ERROR]: Pool element: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:mossy_cobblestone"},"input_predicate":{"block":"minecraft:cobblestone","probability":0.01,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:cobblestone"},"input_predicate":{"block":"minecraft:barrel","probability":0.85,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"rotation":"12"},"Name":"minecraft:wither_skeleton_skull"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.005,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:air"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.6,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"facing":"north","lit":"false","signal_fire":"false","waterlogged":"false"},"Name":"minecraft:campfire"},"input_predicate":{"block":"minecraft:campfire","probability":0.15,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}]}
[11:37:30] [main/ERROR]: Pool element: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:mossy_cobblestone"},"input_predicate":{"block":"minecraft:cobblestone","probability":0.01,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:cobblestone"},"input_predicate":{"block":"minecraft:barrel","probability":0.85,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"rotation":"12"},"Name":"minecraft:wither_skeleton_skull"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.005,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:air"},"input_predicate":{"block":"minecraft:skeleton_skull","probability":0.6,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"facing":"north","lit":"false","signal_fire":"false","waterlogged":"false"},"Name":"minecraft:campfire"},"input_predicate":{"block":"minecraft:campfire","probability":0.15,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}]}
```

</details>

**Comment by RDKRACZ** [comment]
Ok so after I managed to come up with something smart like sorting mods folder content by modification date to know which ones I updated it seems that it may be caused by the following: 
![image](https://user-images.githubusercontent.com/43277609/116866018-fa10fd80-ac0a-11eb-8f67-5404189d4b25.png)

I will try removing them one by one but I saw Blame printing something about Stoneholm before.

**Comment by RDKRACZ** [comment]
Sooo it's caused by FAPI 0.34. Is it possible?

**Comment by TelepathicGrunt** [comment]
can you please post the entire latest.log file instead of snippets? I feel like a lot of info is being missed here

**Comment by TelepathicGrunt** [comment]
I'm able to enter/exit worlds when using latest RS and latest Fapi which leads me to think it's probably another mod breaking my stuff. 
![image](https://user-images.githubusercontent.com/40846040/116868509-e2228500-abdc-11eb-9926-3422a159c03a.png)

**Comment by TelepathicGrunt** [comment]
I just tried it with latest AOF3, updated Fabric API and Cardinal Components to latest, removed GOML, and I was able to create a new world and re-enter it

**Comment by RDKRACZ** [comment]
```
Caused by: java.lang.RuntimeException: Failed to hack fabric API
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:56)
	... 11 more
Caused by: java.lang.NoSuchFieldException: type
	at java.lang.Class.getDeclaredField(Class.java:2411)
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:52)
```

![image](https://user-images.githubusercontent.com/43277609/116870857-93441200-ac13-11eb-8e40-c35214a7fe46.png)

That's why I hate jar-in-jar, I didn't know I have CCA installed. Haven't tested this yet but will reopen (and send full logs) if it turns out it's something else than CCA.

**Comment by RDKRACZ** [comment]
lol you were a few seconds faster
