### ISSUE TITLE
Crash after updating to v1.10.5-fabric

### ISSUE THREAD

**Issue by BrekiTomasson** [TelepathicGrunt/RepurposedStructures-Fabric#113]
I'm getting this crash semi-randomly in newly generated worlds as I travel around.

```
java.lang.IllegalArgumentException: bound must be positive
    at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.8)
    at java.util.Random.nextInt(Random.java:388)
    at net.minecraft.structure.pool.StructurePool.getRandomElement(StructurePool:131)
    at net.minecraft.structure.pool.StructurePoolBasedGenerator.method_30419(StructurePoolBasedGenerator:266)
    at com.telepathicgrunt.repurposedstructures.world.structures.BuriableStructure$Start.init(BuriableStructure.java:45)
    at com.telepathicgrunt.repurposedstructures.world.structures.BuriableStructure$Start.init(BuriableStructure.java:36)
```

This seems to have been introduced in connection with the Icy Pyramid, judging by the use of `BuriableStructure` here. It seems `structureManager` returns an empty `StructurePool`

**Comment by TelepathicGrunt** [comment]
Do you have seasons mod on?

**Comment by BrekiTomasson** [comment]
It just so happens that I do! I'll run some tests without it. Is this a known mod conflict?

**Comment by TelepathicGrunt** [comment]
yep. This is actually a duplication of this report https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/108

I'll close this for now but if your check out the link I gave that goes to seasons's github too, the dev for seasons is working on a fix soon so keep watch on seasons until it updates!
