### ISSUE TITLE
Server Crash on repurposed_structures:village_dark_oak

### ISSUE THREAD

**Issue by BoredBrownBear** [TelepathicGrunt/RepurposedStructures-Fabric#114]
Not sure what's happening though, but here are the logs including the whole crash log.

```
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_1646.handler$bmg000$resetSkinIndexBasedOnBiome(class_1646.java:1681)
	at net.minecraft.class_1646.method_5943(class_1646.java:788)
	at net.minecraft.class_3499.method_17917(class_3499.java:425)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_3499.method_15179(class_3499.java:420)
	at net.minecraft.class_3499.method_15172(class_3499.java:360)
	at net.minecraft.class_3781.method_16626(class_3781.java:125)
	at net.minecraft.class_3790.method_27236(class_3790.java:83)
	at net.minecraft.class_3790.method_14931(class_3790.java:79)
	at net.minecraft.class_3449.method_14974(class_3449.java:76)
	at net.minecraft.class_1959.method_28401(class_1959.java:356)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
```

```
****************** Blame Report 1.16.4-2.4.1 ******************: 

 Structure Name : repurposed_structures:village_dark_oak
 Structure Registry Name : repurposed_structures:village_dark_oak
 Structure Details : com.telepathicgrunt.repurposedstructures.world.structures.GenericJigsawStructure@28c832a9
 Biome Registry Name : minecraft:dark_forest
	Player Count: 1 / 20; [class_3222['invisibleants'/289, l='ServerLevel[world]', x=4338.11, y=66.85, z=1932.75]]
	Data Packs: vanilla, Fabric Mods, file/armor statues v2.8.1.zip, file/graves v2.8.0.zip, file/more mob heads v2.8.2.zip, file/players_drop_heads_3.zip, file/more_shulker_shells_3.zip, file/silence mobs v1.1.0.zip, file/villager workstation highlights v1.1.0.zip, file/track raw statistics v1.4.0.zip, file/track statistics v1.1.0.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

[crash-2021-05-11_00.56.03-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6453791/crash-2021-05-11_00.56.03-server.txt)

**Comment by TelepathicGrunt** [comment]
```at java.util.Random.nextInt(Random.java:388)
	at net.minecraft.entity.passive.VillagerEntity.handler$bmg000$resetSkinIndexBasedOnBiome(VillagerEntity.java:1681)
	at net.minecraft.entity.passive.VillagerEntity.initialize(VillagerEntity.java:788)
	at net.minecraft.structure.Structure.method_17917(Structure.java:425)
	```
	
	Looks like you have another mod messing with villager skins and is crashing when spawning Swamp skinned villagers from repurposed structures. Can you share your mod list? You might have to remove some mods till you find which one it is causing the crash

**Comment by TelepathicGrunt** [comment]
npc-variety-port mod just got an update to fix this crash. You can update the mod and everything should work again!
