### ISSUE TITLE
Demeter crashes RS's structures by breaking its processor files due to block properties added

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures-Fabric#121]
[crash-2021-06-12_00.23.29-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6641181/crash-2021-06-12_00.23.29-server.txt)
MC-Version: 1.16.5
Modversion: 1.11.5

```
Description: Exception generating new chunk

java.lang.IllegalArgumentException: bound must be positive
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at java.util.Random.nextInt(Unknown Source)
	at net.minecraft.structure.pool.StructurePool.getRandomElement(StructurePool:131)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator.method_30419(StructurePoolBasedGenerator:266)
	at com.telepathicgrunt.repurposedstructures.world.structures.GenericJigsawStructure$MainStart.init(GenericJigsawStructure.java:175)
	at com.telepathicgrunt.repurposedstructures.world.structures.GenericJigsawStructure$MainStart.init(GenericJigsawStructure.java:168)
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:261)
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:35)
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator:278)
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:267)
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:51)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by TelepathicGrunt** [comment]
Can you put on the mod called Blame, get the crash again, and then share the latest.log file instead? It'll help see which structure might be broken and give us a hint on which mod it is that is breaking it.

**Comment by TelepathicGrunt** [comment]
Blame mod: https://www.curseforge.com/minecraft/mc-mods/blame-fabric

**Comment by ghost** [comment]
Sure. Give me a moment.

**Comment by ghost** [comment]
Here the Log after crash.

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6641254/latest.log)

**Comment by TelepathicGrunt** [comment]
Ok so it appears one of the mods you have on is adding properties to crops unsafely and that is blowing up the worldgen processor files in my mod and then nukes the structure template pools. Without the pool entries, my structures crashes as a result. Whichever mod that is doing this is gonna blow up other mods and datapacks that uses processor files with crops in them too. 

Do you know which of the mods you have on touches crops besides croptopia? I tested croptopia and it doesnt add properties to blocks so it isnt that mod. If not, may I have an exported zip or profile of your mods? That way I can try testing and removing mods to find which one is causing the issue.

**Comment by ghost** [comment]
If you know how to use "McUpdater" then you can use this to downloads my Modpack. :)
Idk which mod adds "crops".

I have a Modlist with very short Mod-Description. Maybe you find the mod there.
http://game.mineasia.de/downloads/mineasia-alpha/MineAsia-Alpha-Test.xml

Maybe Mystical Agriculture...?

**Comment by TelepathicGrunt** [comment]
Got it. It's Demeter. they are adding block properties unsafely to blocks. Time for me to open an issue report to them lol

Here's the log with Blame stating what processor files from RS was blown up my Demeter. This only had those three mods on:
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6641526/latest.log)

**Comment by TelepathicGrunt** [comment]
Oof. Demeter's github links are dead. I'll read out to the dev on discord to see if they can switch to using [Statement Library](https://www.curseforge.com/minecraft/mc-mods/statement) for adding new blockstates to crops. That lib will make their mod safe with worldgen json that many mods and datapacks uses.

**Comment by ghost** [comment]
Ah okay.
So what should I do now? Waiting 'til the dev update his Mod or better removing it?

**Comment by ghost** [comment]
I have a Log from Server. There are some error too. It's not a crash but some "blame-errors".
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6642381/latest.log)

**Comment by TelepathicGrunt** [comment]
It’s probably best to remove Demeter for now until they update as they cause my warm land ruins to crash, my villages to have no farms, and potentially, many other issues with other mods that has structures with crops. Hopefully they will be able to update soon.

The other blame report, besides the broken processors due to Demeter, are about unregistered ConfiguredFeatures from some mods that need to register them. Unregistered ConfiguredFeatures have the potential to cause other mod’s registered features (like trees or ores) to not spawn in the same biome. But that won’t cause a crash

**Comment by ghost** [comment]
Thanks your info. I reported everything from Blame to the owner of the Mods and currently run the server/client without Demeter.
Thank You for helping me fixing one of X problems I currently have. :D

**Comment by TelepathicGrunt** [comment]
Oof.  I just heard back from the dev. Demeter is no longer maintained and has been deleted. I'll leave this github issue report up for maybe a week or two in case anyone else is still using the mod and gets this crash so they can read this.

![image](https://user-images.githubusercontent.com/40846040/121991395-97646300-cd6d-11eb-8e4f-cec18ca2c135.png)

It sucks to see a mod go out like this

**Comment by TelepathicGrunt** [comment]
Gonna close this report now. I think it has been up long enough to help anyone else know to remove demeter by now.
