### ISSUE TITLE
crash with rs end mineshaft in world blender's dimension. fabric 1.17.1

### ISSUE THREAD

**Issue by Chuunkyz** [TelepathicGrunt/RepurposedStructures-Fabric#143]
[23:53:13] [Worker-Main-4/WARN]: Worker-Main-4 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:658) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.generatePieces(MineshaftEndStructure.java:145) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.init(MineshaftEndStructure.java:124) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:269) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:36) ~[?:?]
	at com.telepathicgrunt.worldblender.dimension.ChunkGeneratorBehavior.placeAllConfiguredStructures(ChunkGeneratorBehavior.java:62) ~[world_blender_fabric-3.0.7+1.17.0.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$cnj000$worldblender_generateAllConfiguredStructures(ChunkGenerator:1541) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:292) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:53) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:644) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
[23:53:13] [Worker-Main-3/WARN]: Worker-Main-3 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:658) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.generatePieces(MineshaftEndStructure.java:145) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.init(MineshaftEndStructure.java:124) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:269) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:36) ~[?:?]
	at com.telepathicgrunt.worldblender.dimension.ChunkGeneratorBehavior.placeAllConfiguredStructures(ChunkGeneratorBehavior.java:62) ~[world_blender_fabric-3.0.7+1.17.0.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$cnj000$worldblender_generateAllConfiguredStructures(ChunkGenerator:1541) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:292) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:53) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:644) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
[23:53:13] [Worker-Main-8/WARN]: Worker-Main-8 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:658) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.generatePieces(MineshaftEndStructure.java:145) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.init(MineshaftEndStructure.java:124) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:269) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:36) ~[?:?]
	at com.telepathicgrunt.worldblender.dimension.ChunkGeneratorBehavior.placeAllConfiguredStructures(ChunkGeneratorBehavior.java:62) ~[world_blender_fabric-3.0.7+1.17.0.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$cnj000$worldblender_generateAllConfiguredStructures(ChunkGenerator:1541) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:292) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:53) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:644) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
[23:53:13] [Worker-Main-7/WARN]: Worker-Main-7 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:658) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.generatePieces(MineshaftEndStructure.java:145) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.init(MineshaftEndStructure.java:124) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:269) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:36) ~[?:?]
	at com.telepathicgrunt.worldblender.dimension.ChunkGeneratorBehavior.placeAllConfiguredStructures(ChunkGeneratorBehavior.java:62) ~[world_blender_fabric-3.0.7+1.17.0.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$cnj000$worldblender_generateAllConfiguredStructures(ChunkGenerator:1541) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:292) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:53) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:644) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
[23:53:13] [Worker-Main-6/WARN]: Worker-Main-6 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:658) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.generatePieces(MineshaftEndStructure.java:145) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.init(MineshaftEndStructure.java:124) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:269) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:36) ~[?:?]
	at com.telepathicgrunt.worldblender.dimension.ChunkGeneratorBehavior.placeAllConfiguredStructures(ChunkGeneratorBehavior.java:62) ~[world_blender_fabric-3.0.7+1.17.0.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$cnj000$worldblender_generateAllConfiguredStructures(ChunkGenerator:1541) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:292) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:53) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:644) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
[23:53:13] [Worker-Main-9/WARN]: Worker-Main-9 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:658) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.generatePieces(MineshaftEndStructure.java:145) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.init(MineshaftEndStructure.java:124) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:269) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:36) ~[?:?]
	at com.telepathicgrunt.worldblender.dimension.ChunkGeneratorBehavior.placeAllConfiguredStructures(ChunkGeneratorBehavior.java:62) ~[world_blender_fabric-3.0.7+1.17.0.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$cnj000$worldblender_generateAllConfiguredStructures(ChunkGenerator:1541) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:292) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:53) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:644) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
[23:53:13] [Server thread/FATAL]: Error executing task on Server
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1155) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:658) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.generatePieces(MineshaftEndStructure.java:145) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at com.telepathicgrunt.repurposedstructures.world.structures.MineshaftEndStructure$MainStart.init(MineshaftEndStructure.java:124) ~[repurposed_structures_fabric-2.3.3+1.17.1.jar:?]
	at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:269) ~[?:?]
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:36) ~[?:?]
	at com.telepathicgrunt.worldblender.dimension.ChunkGeneratorBehavior.placeAllConfiguredStructures(ChunkGeneratorBehavior.java:62) ~[world_blender_fabric-3.0.7+1.17.0.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.handler$cnj000$worldblender_generateAllConfiguredStructures(ChunkGenerator:1541) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:292) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:53) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:644) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:642) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	... 11 more

**Comment by TelepathicGrunt** [comment]
new update released to fix this crash now!
