### ISSUE TITLE
Server crash after 5 sec when join the server

### ISSUE THREAD

**Issue by NantaArthur** [TelepathicGrunt/RepurposedStructures-Fabric#149]
is this crash because of this mod? my server keeps crashing every time I join the server

**Crash Log**

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/17/21, 12:31 PM
Description: Feature placement

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5497.method_31027()" because the return value of "java.util.function.Supplier.get()" is null
	at net.minecraft.class_3781.method_16616(class_3781.java:148)
	at net.minecraft.class_5188.method_16616(class_5188.java:33)
	at net.minecraft.class_3781.method_16626(class_3781.java:124)
	at net.minecraft.class_3790.method_27236(class_3790.java:88)
	at net.minecraft.class_3790.method_14931(class_3790.java:84)
	at net.minecraft.class_3449.method_14974(class_3449.java:97)
	at net.minecraft.class_1959.method_28401(class_1959.java:366)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_1959.method_8702(class_1959.java:365)
	at net.minecraft.class_2794.method_12102(class_2794.java:245)
	at net.minecraft.class_2806.method_12151(class_2806.java:100)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)
	at net.minecraft.class_3898.method_17225(class_3898.java:556)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:550)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3781.method_16616(class_3781.java:148)
	at net.minecraft.class_5188.method_16616(class_5188.java:33)
	at net.minecraft.class_3781.method_16626(class_3781.java:124)
	at net.minecraft.class_3790.method_27236(class_3790.java:88)
	at net.minecraft.class_3790.method_14931(class_3790.java:84)
	at net.minecraft.class_3449.method_14974(class_3449.java:97)
	at net.minecraft.class_1959.method_28401(class_1959.java:366)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
	at it.unimi.dsi.fastutil.longs.LongIterator.forEachRemaining(LongIterator.java:53)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)

-- Feature --
Details:
	Description: ResourceKey[minecraft:worldgen/structure_feature / repurposed_structures:village_oak]
Stacktrace:
	at net.minecraft.class_1959.method_8702(class_1959.java:365)

-- Generation --
Details:
	CenterX: -39
	CenterZ: 5
	Seed: 3349212405271110730
	Biome: net.minecraft.class_1959@3d8e74b4
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:245)
	at net.minecraft.class_2806.method_12151(class_2806.java:100)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)

-- Chunk to be generated --
Details:
	Location: -39,5
	Position hash: 25769803737
	Generator: net.minecraft.class_3754@6f5bcf9d
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:556)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:550)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Affected level --
Details:
	All players: 3 total; [class_3222['YolandaArthur'/647, l='ServerLevel[world]', x=-52.54, y=68.00, z=427.60], class_3222['xielrin'/773, l='ServerLevel[world]', x=-51.50, y=68.00, z=424.09], class_3222['ShibuLilBiscuit'/830, l='ServerLevel[world]', x=-452.31, y=65.00, z=70.12]]
	Chunk stats: 3985
	Level dimension: minecraft:overworld
	Level spawn location: World: (114,63,211), Section: (at 2,15,3 in 7,3,13; chunk contains blocks 112,-64,208 to 127,319,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 47120511 game time, 674873 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 137415 (now: false), thunder time: 134393 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:894)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-1053-gcp
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 10417283240 bytes (9934 MiB) / 15602810880 bytes (14880 MiB) up to 32212254720 bytes (30720 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 85 Stepping 7
	Microarchitecture: Cascade Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 3
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16057.05
	Virtual memory used (MB): 16396.44
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms128M -Xmx30720M
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.3
		additionalbars: Additional Bars 2.1.1
		adorn: Adorn 2.1.5+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.3.0
		amecsapi: Amecs API 1.1.5+mc21w16a
		appletreesrev: Apple Trees Rev. 2.5
		aqupdcaracal: Caracal mob 1.17-1.3.2
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		architects_palette: Architect's Palette Fabric 1.2
		architectury: Architectury 2.5.32
		artifacts: Artifacts 5.0.0+fabric
		artifality: Artifality 0.4.2
		artifice: Artifice 0.15.5+21w07a
		assembly: Assembly 21w06a-1.0.0
		attributefix: Attribute Fix {FABRIC} 1.0.3
		awesomedungeon: Awesome Dungeon 1.1.0
		backslot: BackSlot 1.2.1
		backslotaddon: BackSlot Addon 1.0.6
		battletowers: Battle Towers 3.4.1-1.17.1
		bclib: BCLib 0.3.1
		beaconoverhaul: Beacon Overhaul 1.4.2+1.17
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.11.0-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bfapi: BFAPI 1.1.8
		blockus: Blockus 2.2.10+1.17.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		bountiful: Bountiful 1.0.0
		caelus: Caelus API 0.0.18-1.17.1
		campanion: Campanion 2.0.0-beta.1
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.0
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.4
		charm: Charm 3.3.2
		chord: Chord 1.8.0+1.17-rc1-fabric
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		club_minnced_discord-webhooks: discord-webhooks 0.5.8
		clumps: Clumps 7.0.10
		colytra: Colytra 2.0.0-1.17
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_squareup_okhttp3_okhttp: okhttp 3.14.9
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.7-1.17.1
		companion_bats: Companion Bats 1.17.9
		cosmetic-armor: Cosmetic Armor 1.1.0
		couplings: Couplings 1.5.0+1.17
		crawl: Crawl 0.9.3
		croptopia: Croptopia 1.6.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		customstars: Custom Stars 0.6+1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.6
		decorative: Decorative 4.1.1
		deepslatecutting: Deepslate Cutting 1.2.2
		denseores: Dense Ores: Refabricated 1.1+1.17
		dragonloot: DragonLoot 1.0.9
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.48-fabric
		earthtojavamobs: Earth2Java 1.7.3+1.17
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enhancedcelestials: Enhanced Celestials 2.0.5
		expandability: ExpandAbility 3.0.2
		extended_armor_bars: Extended Armor Bars 1.1.0
		fabric: Fabric API 0.40.8+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabric-tree-chopper: Fabric Tree Chopper 0.7.2
		fabricloader: Fabric Loader 0.11.7
		fabricsit: FabricSit 1.6.3
		fake-player-api: Fake Player API 0.2.0
		farmersdelight: Farmer's Delight 1.17.1-0.1.2
		fdlink: Fabric <-> Discord Link 0.9.8
		fdlink_1_12_2: Fabric <-> Discord Link 0.9.8
		fdlink_1_15_2: Fabric <-> Discord Link 0.9.8
		fdlink_1_16: Fabric <-> Discord Link 0.9.8
		fdlink_1_7_10: Fabric <-> Discord Link 0.9.8
		fdlink_1_8_9: Fabric <-> Discord Link 0.9.8
		fdlink_api: Fabric <-> Discord Link API 0.1.1
		fdlink_common: Fabric <-> Discord Link 0.9.8
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		flesh2leather: Flesh2Leather 1.0.2
		flintytools: Flinty Tools 1.0.0
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		forgottenrecipes: Forgotten Recipes 1.0.3
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		geckolib3: Geckolib 3.0.16
		gimme_bundles: Gimme bundles! 1.0.2
		go-fish: Go Fish 1.3.0-beta-1.17.1
		goblintraders: Goblin Traders 1.1.0
		goldenhoppers: Golden Hoppers 1.1.0
		grass_pass: Grass Bypass 1.0.0
		graveyard: The Graveyard 1.0
		guardiansgalore: GuardiansGalore 1.17.1-2.1
		guild: Guild 0.3.3
		heartbond: Heartbond 1.1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		icarus: Icarus 1.3
		infusion_table: Infusion Table 1.0.2
		inmis: Inmis 2.3.2-1.17.1
		interactic: Interactic 0.1.6-1.17
		io_activej_activej-codegen: activej-codegen 4.3
		io_activej_activej-serializer: activej-serializer 4.3
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		just_end_anchor: Just An End Anchor 1.0.1
		kambrik: Kambrik 1.1.0
		kibe: Kibe 1.9.3-BETA+1.17
		krypton: Krypton 0.1.4
		kubejs: KubeJS 1701.3.10-build.9999
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.4
		lovely_snails: Lovely Snails 1.0.3+1.17
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.17.1
		mcda: MC Dungeons Armors 1.7.13
		mcdar: MC Dungeons Artifacts 1.4.1
		mcdw: MC Dungeons Weapons 3.5.5
		megane: megane 5.5.0
		megane-base: megane-base 5.5.0
		megane-fabric-transfer: megane-fabric-transfer 5.5.0+1.3.0-fc40aa9d18
		megane-kibe: megane-kibe 5.5.0+1.9.1-BETA-1.17
		megane-runtime: megane-runtime 5.5.0
		megane-vanilla: megane-vanilla 5.5.0+1.17.1
		midnightlib: MidnightLib 0.2.5
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		morebannerfeatures: More Banner Features 1.0.7
		morerespawnanchors: More Respawn Anchors 1.0.2
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3-newconfig+mc1.17.1-pre1
		mtr: Minecraft Transit Railway 1.17-3.0.0-beta-8-prerelease-1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		mythic-mounts: Mythic Mounts 1.17.1-2.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nears: Nears 1.1.2
		net_dv8tion_jda: JDA 4.3.0_323
		net_sf_trove4j_trove4j: trove4j 3.0.3
		npcvariety: NPC Variety 2.1.3
		odysseyhud: OdysseyHUD 1.0.0
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_json_json: json 20210307
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		org_yaml_snakeyaml: snakeyaml 1.27
		outvoted: Outvoted 2.0.0-alpha.14
		oxidized: Oxidized 1.4.0
		oxidizelib: OxidizeLib 1.1.0
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		paintings: Paintings ++ 1.17.1-1.0.0.3
		patchouli: Patchouli 1.17.1-56-FABRIC
		paxi: Paxi 1.17-1.2.2
		placeholder-api: Placeholder API 1.1.1+1.17.1
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.6+1.17.1
		polymorph: Polymorph 0.0.14-1.17.1
		promenade: Promenade 2.1.2
		quartzelv: Quartz Elevator 1.2.5
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.3.9+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		respawnablepets: Respawnable Pets 1.17-5
		rhino: Rhino 1605.1.4-build.63
		scorch: Scorch 1.1.2
		seasons: Fabric Seasons 1.3.1-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		sit: Sit 1.17.1-13
		slotlink: slotlink 3.1.6
		snowundertrees: Snow Under Trees 1.0.0
		somnus: Somnus API 0.0.13-1.17.1
		spark: spark 1.6.2
		spirit: Spirit 1.1.0
		starlight: Starlight 1.0.0+fabric.73f6d37
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		structure-helpers: Structure Helpers 3.2.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 1.6.1
		the_aether: The Aether 1.17.1-1.5.0
		the_bumblezone: The Bumblezone - Fabric 3.2.4+1.17.1
		things: Things 0.2.6
		thonkutil: ThonkUtil 1.1.1
		transparent_cosmetics: Transparent Cosmetics 1.3.0
		traverse: Traverse 4.0.0
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.4
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		tweed: Tweed API 3.0.0-beta.22
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		twigs: Twigs 1.0.2
		universal-graves: Universal Graves 1.1.2+1.17.1
		universal_ores: Universal Ores 1.0
		upgradedechests: Upgraded Ender Chests 1.0.2-1.17
		upgradedshulkers: Upgraded Shulkers 1.1.0-1.17
		urns: Urns 1.0.1
		valley: ValleyCraft 1.3.2
		vanilla_degus: Vanilla Degus 1.2.3
		veinmining: Vein Mining 0.0.10-1.17
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.0
		voicechat: Simple Voice Chat 1.17.1-2.0.3
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.1.2
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.7
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		worldedit: WorldEdit 7.2.6+4b2d1e7
		wthit: wthit 3.9.3
		xaerominimap: Xaero's Minimap 21.19.0
		xaeroworldmap: Xaero's World Map 1.17.3
		yungsapi: YUNG's API 1.17-Fabric-19
	Player Count: 3 / 20; [class_3222['YolandaArthur'/647, l='ServerLevel[world]', x=-52.54, y=68.00, z=427.60], class_3222['xielrin'/773, l='ServerLevel[world]', x=-51.50, y=68.00, z=424.09], class_3222['ShibuLilBiscuit'/830, l='ServerLevel[world]', x=-452.31, y=65.00, z=70.12]]
	Data Packs: vanilla, Fabric Mods, minecraft:transparent_cosmetics, file/guild_virtualhome.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by TelepathicGrunt** [comment]
Can you put on this mod called Blame, enter the world and get it to crash again, and then give me the latest.log file please?
https://www.curseforge.com/minecraft/mc-mods/blame-fabric

Not the crashlog file. latest.log file from the log folder will give me all the info i need unlike the crashlog file which is missing a lot of info

**Comment by kotisorion** [comment]
****************** Blame Report Structure NBT 1.17-4.2.0-fabric ******************

 Failed to load structure nbt file from : repurposed_structures:village/badlands/streets/straight_04
 The path represented by this is:  data/repurposed_structures/structures/village/badlands/streets/straight_04.nbt
 Most common cause is that there is a typo in this path to the nbt file.




i think its supposed to be villages not village

**Comment by NantaArthur** [comment]
I'm so sorry for the super late reply, I will upload the modpack tonight.

**Comment by TelepathicGrunt** [comment]
hmm weird. I joined your world and teleported to the oak village and no crash. I started up a server, played for several minutes and then teleported to an oak village and still no crash. Even traveling a bit didn't seem to cause any crash. Just to be clear, you have no datapacks on right?
![image](https://user-images.githubusercontent.com/40846040/138143684-109174b6-4209-44fd-a436-752bfef891d5.png)

**Comment by NantaArthur** [comment]
hi thank you for your response, after I regenerate the world, the problem never occurred again, and this is the log from the previous crash I hope it can help, (´｡• ᵕ •｡`) ♡

https://pastebin.com/7UaFh6bc
