### ISSUE TITLE
Installed no_null_processors, fabric loader complains about unmet dependency

### ISSUE THREAD

**Issue by sorat0mo** [TelepathicGrunt/RepurposedStructures-Fabric#177]
Error log:

```
ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Install no_null_processors, any version.
Unmet dependency listing:
Mod 'Repurposed Structures' (repurposed_structures) 3.3.2+1.18.1 requires any version of no_null_processors, which is missing!
Inactive mods:
mod 'Cardinal Components API (base)' (cardinal-components-base) 4.0.0-alpha.1+21w37a, reason: newer version active
mod 'Cardinal Components API (entities)' (cardinal-components-entity) 4.0.0-alpha.1+21w37a, reason: newer version active
mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: newer version active
mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.6+3ac43d9565, reason: newer version active
mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: newer version active
mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca335c8, reason: newer version active
mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: newer version active
mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: newer version active
mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.3+6b21378a65, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9565, reason: newer version active
mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
mod 'MidnightLib' (midnightlib) 0.2.9, reason: newer version active
mod 'Mod Menu' (modmenu) 3.0.0, reason: newer version active
mod 'OmegaConfig' (omega-config) 1.2.2-1.18.1, reason: newer version active
<html>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)<br/>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)<br/>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)<br/>at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)<br/>at org.multimc.EntryPoint.listen(EntryPoint.java:143)<br/>at org.multimc.EntryPoint.main(EntryPoint.java:34)</html>
```

Repurposed Structures version: v3.3.2
No_Null_Processors version: 2.0.2

**Comment by TelepathicGrunt** [comment]
You downloaded the forge version of no null processor. 
This is the fabric version: https://www.curseforge.com/minecraft/mc-mods/no-null-processors/files/3570785

try with that jar and it should work fine. Usually mod launchers will download the correct file as I made sure the files are properly tagged as forge or fabric

**Comment by TelepathicGrunt** [comment]
Although you may want to wait a bit for the new update anyway as this issue came up
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/178

**Comment by TelepathicGrunt** [comment]
try v3.3.3 now. The automated system I was switching to using for uploading to curseforge grabbed the wrong jar to upload. I went ahead and manually uploaded the correct jar myself while I go work with the dev of the automated task system to figure out what is wrong.
