### ISSUE TITLE
RP 3.3.2 crashes with Fabric 0.12.12

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [TelepathicGrunt/RepurposedStructures-Fabric#178]
java.lang.RuntimeException: Failed to read accessWidener file from mod repurposed_structures
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
	... 3 more

^Crash Log^ Thanks

**Comment by TelepathicGrunt** [comment]
Give me a moment to check something. Might be due to the new system I am using to upload jars to curseforge

**Comment by TelepathicGrunt** [comment]
try v3.3.3 now. The automated system I was switching to using for uploading to curseforge grabbed the wrong jar to upload. I went ahead and manually uploaded the correct jar myself while I go work with the dev of the automated task system to figure out what is wrong.

**Comment by Cr4fTJuNkiE** [comment]
Will do. Thanks TG!

**Comment by Cr4fTJuNkiE** [comment]
Works fine now! Thanks again!
