### ISSUE TITLE
Incompatibility with PolyMC resource generation

### ISSUE THREAD

**Issue by Zekiu** [TelepathicGrunt/RepurposedStructures-Fabric#190]
[PolyMC](https://github.com/TheEpicBlock/PolyMc) is a server-side mod that makes 'non server-side only' mods work with vanilla clients. Starting with Repurposed Structures 4.0.2, PolyMC is unable to successfully generate a resource pack with RS installed. According to the logs, it's caused by something witch hut related

Here's the output of `/polymc generate resources` with only PolyMC, Fabric API and RS with it's dependencies installed on server:
>[22:54:25] [Server thread/INFO]: [Zekiu_: Starting resource generation]
[22:54:25] [Thread-6/INFO]: [Zekiu_: An error occurred whilst trying to generate the resource pack! Please check the console.]
[22:54:25] [Thread-6/INFO]: [STDERR]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 37 column 6 path $.Find all new Witch Huts!
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.Gson.fromJson(Gson.java:978)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.Gson.fromJson(Gson.java:901)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at io.github.theepicblock.polymc.impl.PolyMapImpl.generateResourcePack(PolyMapImpl.java:216)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at io.github.theepicblock.polymc.impl.PolyMcCommands.lambda$registerCommands$3(PolyMcCommands.java:89)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at java.base/java.lang.Thread.run(Thread.java:833)
[22:54:25] [Thread-6/INFO]: [STDERR]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 37 column 6 path $.Find all new Witch Huts!
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:683)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866)
[22:54:25] [Thread-6/INFO]: [STDERR]:   at com.google.gson.Gson.fromJson(Gson.java:963)
[22:54:25] [Thread-6/INFO]: [STDERR]:   ... 4 more

I was unsure where I was supposed to report this issue, but since it only happens with RS installed, I've decided to report it here. :P
I will create a new issue in PolyMC's repository if it turns out to be a PolyMC issue and not a RS issue

**Comment by TelepathicGrunt** [comment]
I think the issue is this line of this Lang files that is missing a , at the end. 

https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/c5d28bbc1283b59e5c62cb166c99e181ee3b2bf7/src/main/resources/assets/repurposed_structures/lang/zh_cn.json#L35

you can datapack replace that file for now to fix it and see if that resolves your issues

**Comment by Zekiu** [comment]
Yup, it works now. I was actually checking the lang files as I suspected it may have been because of them, and zh_cn.json is the only file I didn't check. Talk about coincidence :P
Anyway, it works now with the required change, so this issue can be closed.
