### ISSUE TITLE
Datapack Crash

### ISSUE THREAD

**Issue by Geneticus** [TelepathicGrunt/RepurposedStructures-Fabric#207]
When I try to load an existing save I get an option for safe mode or return to title screen. When I try to create a new game I get a crash. 

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/16/22, 4:02 AM
Description: mouseClicked event handler

java.lang.ClassCastException: class net.minecraft.class_3294$class_7082 cannot be cast to class net.minecraft.class_3262 (net.minecraft.class_3294$class_7082 and net.minecraft.class_3262 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @21a947fe)
	at com.telepathicgrunt.repurposedstructures.utils.GeneralUtils.getAllFileStreams(GeneralUtils.java:244)
	at com.telepathicgrunt.repurposedstructures.utils.GeneralUtils.getAllDatapacksJSONElement(GeneralUtils.java:273)
	at com.telepathicgrunt.repurposedstructures.misc.structurepiececounter.StructurePieceCountsAdditionsMerger.performCountsAdditionsDetectionAndMerger(StructurePieceCountsAdditionsMerger.java:26)
	at com.telepathicgrunt.repurposedstructures.misc.structurepiececounter.StructurePieceCountsManager.apply(StructurePieceCountsManager.java:69)
	at com.telepathicgrunt.repurposedstructures.misc.structurepiececounter.StructurePieceCountsManager.method_18788(StructurePieceCountsManager.java:24)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.class_525.method_31130(class_525.java:158)
	at net.minecraft.class_526.method_19944(class_526.java:72)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.telepathicgrunt.repurposedstructures.utils.GeneralUtils.getAllFileStreams(GeneralUtils.java:244)
	at com.telepathicgrunt.repurposedstructures.utils.GeneralUtils.getAllDatapacksJSONElement(GeneralUtils.java:273)
	at com.telepathicgrunt.repurposedstructures.misc.structurepiececounter.StructurePieceCountsAdditionsMerger.performCountsAdditionsDetectionAndMerger(StructurePieceCountsAdditionsMerger.java:26)
	at com.telepathicgrunt.repurposedstructures.misc.structurepiececounter.StructurePieceCountsManager.apply(StructurePieceCountsManager.java:69)
	at com.telepathicgrunt.repurposedstructures.misc.structurepiececounter.StructurePieceCountsManager.method_18788(StructurePieceCountsManager.java:24)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.class_525.method_31130(class_525.java:158)
	at net.minecraft.class_526.method_19944(class_526.java:72)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Steven's+Traditional+§8-§7+1.19§8.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 663989904 bytes (633 MiB) / 1577058304 bytes (1504 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2204
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 75132.05
	Virtual memory used (MB): 32884.54
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 78.41
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.0.0
		advancedcompass: Advanced Compass 1.2.11
		advancednetherite: Advanced Netherite 1.6.1-1.19
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.3
		architectury: Architectury 5.6.22
		badpackets: Bad Packets 0.1.2
		boatjump: BoatJump 1.1.0-1.19
		bookshelf: Bookshelf 14.0.2
		borderlessmining: Borderless Mining 1.1.3+1.19
		bundlesunlocked: Bundles Unlocked 1.0.3
		chickensshed: ChickensShed 1.19-1.3.1-fabric
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		couplings: Couplings 1.9.0+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
		craftsaddles: Craft Saddles 1.0.2
		diggusmaximus: Diggus Maximus 1.5.6-1.19
			kyrptconfig: Kyrpt Config 1.4.6-1.19
				blue_endless_jankson: jankson 1.2.1
		dimcoordconv: Dimension Coordinate Converter 1.1.2
		enchdesc: EnchantmentDescriptions 11.0.2
		endportalrecipe-fabric: End Portal Recipe (Fabric) 2.7
		fabric: Fabric API 0.55.3+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.6+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.12+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.16+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.24+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.9+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.7+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.8+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.7
		fallingtree: FallingTree 3.6.1
		fwaystones: Fabric Waystones 3.0.0
		geckolib3: Geckolib 3.1.2
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.3
		glassdoor: Glass Doors 3.0.0-rc.1+1.19
		graveyard: The Graveyard 1.10
			omega-config: OmegaConfig 1.2.2-1.18.1
		graveyard_biomes: The Graveyard Biomes 1.2
		guardvillagers: Guard Villagers Fabric 1.19-1.0.14
		held-item-info: Held Item Info 1.3.0
		hopobettermineshaft: Hopo Better Mineshaft 1.1.4
		immersive_portals: Immersive Portals 2.0.1
			imm_ptl_core: Immersive Portals Core 2.0.1
			q_misc_util: QMiscUtil 2.0.1
		indium: Indium 1.0.4+mc1.19
		infinitevillagertrading: InfiniteVillagerTrading 1.19-fabric0.53.3-1.1
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lava_walker: LavaWalker Fabric-1.19-0.1.2
		minecraft: Minecraft 1.19
		mining_helmet: Mining Helmet 1.1.1+1.19
		mob_catcher: Mob Catcher 1.2.10
		modmenu: Mod Menu 4.0.0
		morevillagers: More Villagers 4.0.1
		morezombievillagers-fabric: More Zombie Villagers (Fabric) 1.7
		mousetweaks: Mouse Tweaks 2.22
		oresdropmoresthree: OresDropMoresThree Fabric Mod 1.2.0-1.19
		overpoweredmending: OverpoweredMending 2.5.1
		pehkui: Pehkui 3.3.2+1.14.4-1.19
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		quartzelv: Quartz Elevator 2.1.3+1.19
		recycleiron: Recycle Iron 1.0.2
		repurposed_structures: Repurposed Structures 6.0.1+1.19
			midnightlib: MidnightLib 0.5.2
		reputation: Your Reputation 0.1.3+1.19
		ring_of_attraction: Ring Of Attraction 1.3.8
		ring_of_enderchest: Ring of Enderchest 1.38
		ring_of_growth: Ring Of Growth 1.3.8
		ring_of_miner: Ring Of Miner 1.4.10
			pugh_tools: Pugh Tools 1.3.10
		ring_of_teleport: Ring Of Teleport 1.2.9
		roughlyenoughitems: Roughly Enough Items 9.0.480
		simple_backpack: SimpleBackpack 1.3.15
		simply_houses: Simply Houses 1.1.2-1.19
		sizeshiftingpotions: Size Shifting Potions 1.4.2
		smallernetherportals-fabric: Smaller Nether Portals (Fabric) 2.0
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sparkle: Sparkle 1.0.0
		terrablender: TerraBlender 2.0.0.111
		torch-hit: Torch hit! 1.19-2.0.0.0-fabric
		torchbowmod: TorchBowMod 1.0
		trinkets: Trinkets 3.4.0
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		villagerdrops: Villagers Drop Emeralds on Death 1.1.0
		villagers-follow-emeralds: Villagers Follow Emeralds 1.3.0
		wands: Building Wands 2.5.1_mc1.19
		wardenloot: Warden Loot 1.0.0-1.19
		wooltostring: Wool-to-String 1.0.2
		world-stripper: World Stripper 1.19-3.1.0-Fabric
		wthit: wthit 5.2.1
		xaerominimap: Xaero's Minimap 22.9.2
		xaeroworldmap: Xaero's World Map 1.23.2
		zombievillagersfromspawner-fabric: Zombie Villagers From Spawner (Fabric) 1.7
	Loaded Shaderpack: ComplementaryShaders_v4.5.zip
		Profile: Custom (+8 options changed by user)
	Launched Version: fabric-loader-0.14.7-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3090/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Steven's+Traditional+§8-§7+1.19§8.zip
	Current Language: English (US)
	CPU: 20x Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz

**Comment by TelepathicGrunt** [comment]
This is fixed in v6.0.2 now
