### ISSUE TITLE
Nether Structure Gen Crashes Server

### ISSUE THREAD

**Issue by RawrMaoster** [TelepathicGrunt/RepurposedStructures-Fabric#40]
When one of my players goes into a nether portal the server crashes.

Heres a Crash Report: **https://pastebin.pl/view/6fde65cf**

Summary:
Time: 2020-10-24 02:50:07 CEST
Description: Exception in server tick loop
 
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
    at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
    at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
    at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
    at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Caused by: net.minecraft.class_148: Exception generating new chunk
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:579)
    at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
    ... 11 more
Caused by: java.lang.IllegalArgumentException: bound must be positive
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at java.util.Random.nextInt(Random.java:388)
    at net.minecraft.structure.pool.StructurePool.getRandomElement(StructurePool:131)
    at net.minecraft.structure.pool.StructurePoolBasedGenerator.method_30419(StructurePoolBasedGenerator:266)
    at com.telepathicgrunt.repurposedstructures.world.structures.pieces.GeneralJigsawGenerator.addPieces(GeneralJigsawGenerator.java:23)
    at com.telepathicgrunt.repurposedstructures.world.structures.TempleNetherStructure$Start.init(TempleNetherStructure.java:38)
    at com.telepathicgrunt.repurposedstructures.world.structures.TempleNetherStructure$Start.init(TempleNetherStructure.java:31)
    at net.minecraft.world.gen.feature.StructureFeature.tryPlaceStart(StructureFeature:261)
    at net.minecraft.world.gen.feature.ConfiguredStructureFeature.tryPlaceStart(ConfiguredStructureFeature:35)
    at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStart(ChunkGenerator:278)
    at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:267)
    at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus:51)
    at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
    ... 14 more

**Comment by TelepathicGrunt** [comment]
This is actually a repeat of this issue report https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/36

basically, the problem is due to Trees Don't Float's way of adding new properties to blocks. When they do so, it breaks how Minecraft parses my structure processor json files and so, the nether temple structure pools gets tossed out. Thus, when Minecraft tries to generate my temples, it finds that the pool is empty cause it tossed it out and so it crashes. 

I made an issue report to Trees Don't Float here: https://github.com/grondag/trees-dont-float/issues/21

The solution right now is to take off either Trees Don't Float or take off Repurposed Structures. I hope this helps!

**Comment by RawrMaoster** [comment]
Great to know. Speedy response. TDBF is being eliminated. 

Hope it gets fixed <3 That helped.
