### ISSUE TITLE
Glimmering Potions crash Villager's AI in any village including Repurposed Structures's

### ISSUE THREAD

**Issue by Mewtwoy** [TelepathicGrunt/RepurposedStructures-Fabric#64]
Description: Ticking entity

java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135)
    at net.minecraft.entity.ai.brain.task.GoToWorkTask.run(GoToWorkTask:531)
    at net.minecraft.entity.ai.brain.task.GoToWorkTask.run(GoToWorkTask:23)
    at net.minecraft.entity.ai.brain.task.Task.tryStarting(Task:49)
    at net.minecraft.entity.ai.brain.Brain.startTasks(Brain:506)
    at net.minecraft.entity.ai.brain.Brain.tick(Brain:465)
    at net.minecraft.entity.passive.VillagerEntity.mobTick(VillagerEntity:272)
    at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:744)
    at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2508)
    at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:542)
    at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
    at net.minecraft.entity.LivingEntity.tick(LivingEntity:2254)
    at net.minecraft.entity.mob.MobEntity.tick(MobEntity:342)
    at net.minecraft.entity.passive.VillagerEntity.tick(VillagerEntity:313)
    at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
    at net.minecraft.class_3218$$Lambda$7489/1322030875.accept(Unknown Source)
    at net.minecraft.world.World.tickEntity(World:561)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at net.minecraft.server.MinecraftServer$$Lambda$7048/1043748215.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

Mods which potentially have issues: Mostructures, glimmering potions.
I removed mods one by one, until i narrowed it down to these.

**Comment by TelepathicGrunt** [comment]
My mod doesnt touch villager AI so this is more likely to be another mod's issue or a vanilla bug. Which biome were you in when the crash occurred? I'll take a quick look with those mods on.

**Comment by TelepathicGrunt** [comment]
Ah I see you reported it to https://github.com/Draylar/glimmering-potions/issues/11 and https://github.com/frqnny/mostructures/issues/16.
You can close your report at Mo Structures as I just reproduced this crash with just Glimmering Potions on and teleported to a vanilla village. Something in their logic caused the villager ai to die. I'll leave this report open for others to see in case people get the same crash and wonder what's going on until glimmering potion fixes it.

**Comment by TelepathicGrunt** [comment]
Glimmering Potions just release a fix on their end to fix the crash!
